#!/bin/bash
# This script is needed to modify the target-tracking subsystem
# to allow Clearpath Robotics' wireless charger docking (originally
# developped for GPS navigation) to be used with IndoorNav

echo "Docking no longer supported; sorry."
